### ISSUE TITLE
Bug: gif and sticker buttons stay

### ISSUE THREAD

**Issue by Inve1951** [blueb442/enhanceddefault#1]
The gif and sticker buttons stay visible if the client is set to a language other than English.
I'm not sure how to fix this without adding all localizations to the selector and still supporting plugin-added buttons.

![image](https://user-images.githubusercontent.com/18194808/132066707-4542b309-b4ae-43af-841b-d5e37f4a0a1d.png)

If all plugins adding buttons add a way to select them then maybe something like this works:

```css
.buttons-3JBrkn > button ~ .buttonContainer-28fw2U:not(:last-child):not(:matches(
  .invisibleTyping,
  .sendButton,
  ....
)) {
  display: none;
}
```

If they don't, they should add it.
